### ISSUE TITLE
checkNeedsUpdate not working with iOS apps for limited countries

### ISSUE THREAD

**Issue by se09deluca** [SudoPlz/sp-react-native-in-app-updates#64] opened 2022-01-15 18:18 UTC
Hi, 
currently the iOS apps limited to certain country are not found by the lookup api of iTunes, because of a country code filter needed that is missing.
I propose to update react-native-siren to the newest version ([currently v0.0.5](https://github.com/GantMan/react-native-siren/releases)) and adds an optional country param to CheckOptions, than pass down to Siren's performCheck function.

Let me know if you agree..
I can help with a pull request.

Bye 👋🏻

**Comment by SudoPlz** [comment] 2022-01-17 13:52
Duplicate of https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/55 let's track it there.

**Closed by SudoPlz** 2022-01-17 13:52 UTC
