### ISSUE TITLE
In App Updates not Working

### ISSUE THREAD

**Issue by DavidInojosa** [SudoPlz/sp-react-native-in-app-updates#32] opened 2021-07-13 20:20 UTC
This is my code, I used the implementation listed on Readme file. When I run on closed test Alpha at PlayStore it doesn't popup any update component. I don't understand what is wrong.

I implemented also " implementation 'com.google.android.play:core:1.10.0' " on android/app/build.gradle.

APP VERSION CODE BEFORE: 25
APP VERSION NAME BEFORE: 1.8

APP VERSION CODE AFTER: 26
APP VERSION NAME AFTER: 1.9

```
const App = () => {
  LogBox.ignoreAllLogs();
  const inAppUpdates = new SpInAppUpdates(
    false // isDebug
  );
  // curVersion is optional if you don't provide it will automatically take from the app using rn-device-info

  useEffect(() => {
    inAppUpdates.checkNeedsUpdate().then((result) => {
      if (result.shouldUpdate) {
        let updateOptions = {};
        if (Platform.OS === 'android') {
          // android only, on iOS the user will be promped to go to your app store page
          updateOptions = {
            updateType: IAUUpdateKind.IMMEDIATE,
          };
        }
        inAppUpdates.startUpdate(updateOptions);
      }
    });
  }, []);

  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        <StatusBar
          barStyle="light-content"
          backgroundColor={DARK_ACCENT_GREEN}
        />
        <Routes />
        <FlashMessage position="bottom" />
      </PersistGate>
    </Provider>
  );
};

export default App;
```

**Comment by shubhamdeol** [comment] 2021-07-17 05:35
@DavidInojosa Have you make it work. Same happens for me. I can see ```shouldUpdate``` returning true, but when calling startUpdate function nothing is happening.

I have also installed
```implementation 'com.google.android.play:core:1.10.0```

**Comment by DavidInojosa** [comment] 2021-07-17 19:36
> @DavidInojosa Have you make it work. Same happens for me. I can see `shouldUpdate` returning true, but when calling startUpdate function nothing is happening.
> 
> I have also installed
> `implementation 'com.google.android.play:core:1.10.0`

No, if you have any news or why it is not working, remember answering here please. Still trying to figure out what is happening.

**Comment by SudoPlz** [comment] 2021-07-19 08:45
@shubhamdeol I'm afraid this has to be done with debugging. We can set up a call and work together on debugging it since I understand it may be difficult to create a reproduction project for in-app-updates.

**Comment by shubhamdeol** [comment] 2021-07-19 09:01
@DavidInojosa @SudoPlz I have figured out some issues I had using the library. some of  the ```Types```  library is exporting are coming as undefined, but not giving any import error. 

I had to define these two types in my code by myself instead of getting from library.

```js
const AndroidUpdateType = {
  FLEXIBLE: 0,
  IMMEDIATE: 1,
};

 enum InstallationStatus {
  UNKNOWN = 0,
  PENDING = 1,
  DOWNLOADING = 2,
  INSTALLING = 3,
  INSTALLED = 4,
  FAILED = 5,
  CANCELED = 6,
  DOWNLOADED = 11,
}
```  
Now In app update is working as expected. I had to put some alerts and redeploy app in internal app sharing around 10-20 times to figure this out.  

Here is how to use.

Inside useEffect

```js
 React.useEffect(() => {
    InteractionManager.runAfterInteractions(async () => {
      const result = await inAppUpdates.checkNeedsUpdate();
      setNeedsUpdate(result.shouldUpdate);
      setAndroidOtherInfo(result.other as AndroidInAppUpdateExtras);
    });
  }, []);
```
Render some button in UI which shows up when ```shouldUpdate``` is true and on its press call ```startUpdate``` method

```js
     const startUpdate = async () => {
    try {
      if (androidOtherInfo) {
        const isImmediate =
          androidOtherInfo?.updatePriority >= HIGH_PRIORITY_UPDATE;
        await inAppUpdates.startUpdate({
          updateType: isImmediate
            ? AndroidUpdateType.IMMEDIATE
            : AndroidUpdateType.FLEXIBLE,
        });
        inAppUpdates.addStatusUpdateListener(onStatusUpdate);
      }
    } catch (error) {
      captureJsException(error, 'feature', 'in_app_update');
    }
  };
  
  
  const onStatusUpdate = (eventInfo: StatusUpdateEvent) => {
    if (eventInfo) {
      if (eventInfo.status === InstallationStatus.DOWNLOADED) {
        setUpdateInfo(null);
        inAppUpdates.installUpdate();
      } else {
        setUpdateInfo(eventInfo);
      }
    }
  };


```

```setUpdateInfo``` sets the update like how many bytes are being downloading out of how many. 

@SudoPlz Thanks a lot for offering setup call. Really appreciate this gesture.

**Comment by SudoPlz** [comment] 2021-07-19 09:09
No worries @shubhamdeol I'm glad you figured that out.
So long story short, are the `AndroidUpdateType` values that are problematic (because they're undefined for some reason ???) or did you find more exported values being undefined?

Do you think you can push a PR with a fix please?

Thank you

**Comment by shubhamdeol** [comment] 2021-07-19 09:10
I found only **AndroidUpdateType** and **InstallationStatus** values to be undefined

**Comment by SudoPlz** [comment] 2021-07-19 09:16
@shubhamdeol where were those values undefined? In the library itself, or in your code (I'm actually asking if you tried to use those values on your end i.e like `AndroidUpdateType.FLEXIBLE` instead of `IAUUpdateKind.FLEXIBLE`)

**Comment by shubhamdeol** [comment] 2021-07-19 09:21
If I was importing LIke I was getting error can not read property of undefined. ```command``` + clicking on these types was taking me to their definition. But I was still getting these values as undefined in my run time production environment. 
```js
import {
  InstallationStatus,
  AndroidUpdateType,
} from 'sp-react-native-in-app-updates';
```

So I removed these imports and defined my own types as

```
const AndroidUpdateType = {
  FLEXIBLE: 0,
  IMMEDIATE: 1,
};

export enum InstallationStatus {
  UNKNOWN = 0,
  PENDING = 1,
  DOWNLOADING = 2,
  INSTALLING = 3,
  INSTALLED = 4,
  FAILED = 5,
  CANCELED = 6,
  DOWNLOADED = 11,
}
```

And things worked fine for me.

**Comment by SudoPlz** [comment] 2021-07-19 09:25
Ok I see what's going on here..

```
import {
  InstallationStatus,
  AndroidUpdateType,
} from 'sp-react-native-in-app-updates';
```

are not exported anywhere like so, instead they are renamed and exported with another name:

https://github.com/SudoPlz/sp-react-native-in-app-updates/blob/master/src/index.d.ts#L12

i.e `AndroidUpdateType` is exported as `IAUUpdateKind`.

Todays editors are smart enough to detect a value, but sometimes not smart enough to know it's not exported, that's why clicking it took you to the definition.

Had you used `IAUUpdateKind` instead like so:

```
import {
  IAUUpdateKind,
} from 'sp-react-native-in-app-updates';
```

I feel that it would've worked.

**Comment by shubhamdeol** [comment] 2021-07-19 09:35
Yes. This should work. Getting a type error though. 

![Screenshot 2021-07-19 at 3 02 31 PM](https://user-images.githubusercontent.com/11364449/126138525-3d4dcda4-fe88-443c-9320-64e3d9535783.png)

May be you are also doing ```export * from './types';``` thats why other type definitions are also being available

**Comment by SudoPlz** [comment] 2021-07-19 09:36
ooh interesting 🤔 , I can see how that led to confusion..

**Comment by SudoPlz** [comment] 2021-07-19 10:08
Could you please check if that's fixed on 1.1.2 ?

I'd be grateful
Thank you

**Comment by DavidInojosa** [comment] 2021-07-19 15:51
I verified what was happening, maybe it could be added to README, I've received undefined because when the In app Update API gets the version of my App, it takes from release mode app (the one active on playstore/appstore), and the version was 1.3.6+7, but In App Updates doesn't read the "+" symbol, so this was the error, I did a update with version 1.3.7 and it worked.

So for me the error was: "+" on version released at playstore.

**Comment by SudoPlz** [comment] 2021-07-19 15:57
Was `1.3.6+7,` the version code? or the version name?

Can you explain a bit further?

Thanks

**Comment by DavidInojosa** [comment] 2021-07-19 17:26
Version Code was 15
Version Name 1.3.0+7

The error was the "+".
So I sent a new release:
Version Code: 15
Version Name: 1.3.7

And In App Update worked.
I didn't see any rule about the "+" symbol for version name work with In App Update, hope this issue help someone else.

**Comment by SudoPlz** [comment] 2021-07-19 17:30
Ok cool, so this falls in place along with the rest of the [version name/code changes](https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/9#issuecomment-856176768) I have to make.
Closing this in favour of an upcoming pr .

**Closed by SudoPlz** 2021-07-19 17:30 UTC

**Comment by Matheuschn** [comment] 2022-03-21 21:27
This import issue is still happening as of version 1.1.7.
Importing AndroidInstallStatus makes it so the object is undefined. Importing IAUInstallStatus fixed the issue.

**Comment by sk02769** [comment] 2022-12-14 11:39
> This is my code, I used the implementation listed on Readme file. When I run on closed test Alpha at PlayStore it doesn't popup any update component. I don't understand what is wrong.
> 
> I implemented also " implementation 'com.google.android.play:core:1.10.0' " on android/app/build.gradle.
> 
> APP VERSION CODE BEFORE: 25 APP VERSION NAME BEFORE: 1.8
> 
> APP VERSION CODE AFTER: 26 APP VERSION NAME AFTER: 1.9
> 
> ```
> const App = () => {
>   LogBox.ignoreAllLogs();
>   const inAppUpdates = new SpInAppUpdates(
>     false // isDebug
>   );
>   // curVersion is optional if you don't provide it will automatically take from the app using rn-device-info
> 
>   useEffect(() => {
>     inAppUpdates.checkNeedsUpdate().then((result) => {
>       if (result.shouldUpdate) {
>         let updateOptions = {};
>         if (Platform.OS === 'android') {
>           // android only, on iOS the user will be promped to go to your app store page
>           updateOptions = {
>             updateType: IAUUpdateKind.IMMEDIATE,
>           };
>         }
>         inAppUpdates.startUpdate(updateOptions);
>       }
>     });
>   }, []);
> 
>   return (
>     <Provider store={store}>
>       <PersistGate persistor={persistor}>
>         <StatusBar
>           barStyle="light-content"
>           backgroundColor={DARK_ACCENT_GREEN}
>         />
>         <Routes />
>         <FlashMessage position="bottom" />
>       </PersistGate>
>     </Provider>
>   );
> };
> 
> export default App;
> ```

**Comment by sk02769** [comment] 2022-12-14 11:39
I need help regrading this

**Comment by sk02769** [comment] 2022-12-14 11:40
Can you show me little code  see how I'm writing

import React from 'react';
import MainNavigator from './src/navigations/MainNavigator.js';
import SpInAppUpdates, {
  NeedsUpdateResponse,
  IAUUpdateKind,
  StartUpdateOptions,
} from 'sp-react-native-in-app-updates';
import {store} from './src/redux/store.js';
import {Provider} from 'react-redux';
export default function App() {
  const inAppUpdates = new SpInAppUpdates(
    false // isDebug
  );
  inAppUpdates.checkNeedsUpdate({}).then((result) => {
    if (result.shouldUpdate) {
      let updateOptions: StartUpdateOptions = {};
      if (Platform.OS === 'android') {
        // android only, on iOS the user will be promped to go to your app store page
        updateOptions = {
          updateType: IAUUpdateKind.IMMEDIATE,
        };
      }
      inAppUpdates.startUpdate(updateOptions); // https://github.com/SudoPlz/sp-react-native-in-app-updates/blob/master/src/types.ts#L78
      inAppUpdates.installUpdate();
    }
  });
  return (
    // <Provider store={store}>
      <MainNavigator />
    // </Provider>
  );
}
