### ISSUE TITLE
Compile time Error

### ISSUE THREAD

**Issue by godbright** [SudoPlz/sp-react-native-in-app-updates#125] opened 2023-01-31 12:51 UTC
Task :app:checkDebugDuplicateClasses FAILED , This is the error i face when i use this packahe

**Comment by SudoPlz** [comment] 2023-01-31 14:03
Duplicate of https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/124

**Closed by SudoPlz** 2023-01-31 14:03 UTC
